### ISSUE TITLE
PSET does not respect _DEST 

### ISSUE THREAD

**Issue by RetroNick2020** [boxgaming/qbjs#101]
if we set the _DEST to Image PSET does not draw on Image

eg.
SCREEN _NEWIMAGE(800,600,32)
dim vimage
vimage = _NEWIMAGE(64,64,32)
_DEST vimage
PSET (1,1),_RGBA(255,255,255,255)    
'works if we replace PSET with 
'LINE (1,1)-(1,1),_RGBA(255,255,255,255),BF
_DEST 0
_putimage (0,0),vimage

**Comment by boxgaming** [comment]
Thank you for reporting.  This issue is related to issue #80.  This has been fixed and will be included in the 0.8.0 release which should be published in the next few days.

It has been published to the qbjs dev server here: https://boxgm.itch.io/qbjs-dev if you’d like to test the fix in the meantime.
